import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProfileTile from "@/app/{componets}/ProfileTile"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="head flex justify-center items-center">
          <ProfileTile></ProfileTile>
        </div>
        </body>
    </html>
  );
}
